### ISSUE TITLE
Incorrect locations sent in 0.2.8

### ISSUE THREAD

**Issue by pkmnfrk** [Electro1512/MetroidAPrime#10]
Archipelago version: 0.5.0
Metroid Prime APWorld: 0.2.8
Dolphin Version: Tested on latest PrimeHack (5.0-20359-dirty) and latest Dolphin release (2407-97)

Description: When collecting some items, additional location checks besides the one actually collected will be sent from the client as though the player collected them. They remain uncollected in-game, but do nothing when collected for real.

Expected Behaviour: Only the collected locations are sent.
Actual Behaviour: Arbitrary other locations are sent. These don't appear to be random, but I do not know the relation between them.

Example:
![image](https://github.com/user-attachments/assets/7f4fdc5e-b177-456e-a7a6-1914c736ce0d)

In this example, I performed the following steps (in both Dolphin versions):
1. Go to Hive Totem and collected the Missile Expansion
2. The Missile Expansion was sent, and the item received
3. Proceed into Transport Access North and collect the other Missile Expansion
4. The locations for Ruined Fountain, Transport Access North, and Main Plaza - Grapple Ledge were all sent, and the items received.

The generated seed:
[AP_23636518179182859652.zip](https://github.com/user-attachments/files/16355987/AP_23636518179182859652.zip)

**Comment by pkmnfrk** [comment]
Although this issue hasn't been acknowledged, it seems the issue has been fixed nonetheless, so closing

**Comment by hesto2** [comment]
@pkmnfrk Sorry 😅 I just recently realized I don't have notifications enabled for this repo!
