### ISSUE TITLE
Linux Archipelago Support

### ISSUE THREAD

**Issue by GFreak01** [Electro1512/MetroidAPrime#6]
Dragging the libs file into the folder doesn't work on Linux.

**Comment by hesto2** [comment]
@GFreak01 Can you give this a whirl now that everything is baked into the apworld?

**Comment by GFreak01** [comment]
It looks like the client is working better.  However, once connected to Dolphin, I end up getting a memory error and it doesn't seem to be tracking any checks.  Attached are 2 screenshots, one of the memory error and one after I unlocked the missiles without any check going through and not actually receiving items.
![Screenshot_20240723_185130](https://github.com/user-attachments/assets/ea791f0b-1e11-488c-84cc-6fee399fd582)
![Screenshot_20240723_184821](https://github.com/user-attachments/assets/977bb7f2-dc36-430a-939e-eea9ead7e02b)

**Comment by hesto2** [comment]
Ah this should be resolved in v0.2.11, can you give that a whirl?

**Comment by GFreak01** [comment]
It's working great!  Thanks for all the hard work!
